FROM python:3.11-slim

WORKDIR /app

RUN pip install asyncssh redis

COPY simulator/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY simulator/ .

CMD ["python", "main.py"]
